name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Acquire and configure Conan
        run: |
          pip3 install conan
          export PATH=/home/runner/.local/bin:$PATH
          conan profile detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build or acquire dependencies
        run: |
          export CONAN_SYSREQUIRES_MODE=enabled
          conan install . --build=missing

      - name: Run the actual build
        run: perl build.pl

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Acquire and configure Conan
        run: |
          pip3 install conan
          export PATH=/home/runner/.local/bin:$PATH
          conan profile detect

      - name: Build or acquire dependencies
        run: conan install . --build=missing

      - name: Run the actual build
        run: perl build.pl

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Acquire and configure Conan
        run: |
          pip3 install conan
          conan profile detect

      - name: Build or acquire dependencies
        run: conan install . --build=missing

      - name: Run the actual build
        run: perl build.pl

